### ISSUE TITLE
Generating all grounded actions for a problem instance 

### ISSUE THREAD

**Issue by urbanm30** [JuliaPlanners/PDDL.jl#7]
Hello! Is there any way of creating all possible grounded actions for a problem instance? I was able to generate all grounded actions for a state but not all possible actions. It would be really handy for my ASnet implementation in Julia.

Thank you for this great package!

**Comment by ztangent** [comment]
Hi! Glad you're finding the package useful, and awesome to hear you're trying to implement ASnet in Julia! :)

It's interesting that you ask about grounding, because I'm actually in the middle of implementing grounding-related functionality. Unfortunately that might still take some time to implement fully. In the meantime though, here's a code snippet that will hopefully be enough for your purposes:

```julia
using PDDL: Domain, State, Action, Compound
using PDDL: get_objects, get_argtypes, get_actions

function groundargs(domain::Domain, state::State, action::Action)
    iters = (get_objects(domain, state, ty) for ty in get_argtypes(action))
    return Iterators.product(iters...)
end

function groundactions(domain::Domain, state::State)
    all_actions = Compound[]
    for (name, action) in get_actions(domain)
        for args in groundargs(domain, state, action)
            ground_act = Compound(name, collect(args))
            push!(all_actions, ground_act)
        end
    end
    return all_actions
end
```

Several points of note:

- This will work with the master branch of the repo / PDDL 0.2.0, but not the Julia registry version of PDDL.jl
- You'll need to supply the initial state for the problem instance, constructed by `initstate(domain, problem)`
- This implementation will not automatically filter out actions whose preconditions are never satisfiable (e.g. if there are static predicates in an action's precondition that are always false) -- you'll have to write additional code that uses the `infer_static_fluents` helper function in order to filter those out.

Hope this helps! Leaving open the issue for a more official solution in the future.

**Comment by urbanm30** [comment]
Thank you so much! I'll look into it, I'm pretty sure it's going to help a ton :)

**Comment by ztangent** [comment]
@urbanm30 I've just pushed some changes to the `master` branch implementing grounding related functionality that you can check out here: https://github.com/JuliaPlanners/PDDL.jl/tree/master/src/grounding

The function you want is probably `groundactions`:

https://github.com/JuliaPlanners/PDDL.jl/blob/be1ece32d0eba56d001a74e122dbc1e1a5ffabe0/src/grounding/action.jl#L96-L106

In contrast to the snippet I pasted earlier, this returns a list of `GroundAction` objects, the `term` property of which will give you the corresponding `Term` label. So you might have to change some of your code if you'd like to switch to what I've implemented. On the plus side, the new implementation automatically does static checks and eliminates actions that are never available, e.g. `(stack a a)` (stacking block a on itself).

You'll probably want to update to the latest commit of the `refactor` on SymbolicPlanners.jl as well, to prevent errors, and to take advantage of the reimplemented HSP and FF heuristics (if you were using them), which are orders of magnitude faster now.
